#!/usr/bin/env bash
#
# scripts/create_issues.sh - Batch GitHub Issue Creator Template
# Generated by swe-skills github-issues-script
#

set -e

DRY_RUN=false
INTERACTIVE=true
TARGET_REPO=""

usage() {
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  --dry-run      Print issue titles and bodies without creating them"
    echo "  --all, -y      Create all issues automatically without per-issue confirmation"
    echo "  --repo <owner/repo> Override target GitHub repository"
    echo "  -h, --help     Show this help message"
    exit 0
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run) DRY_RUN=true; shift ;;
        --all|-y) INTERACTIVE=false; shift ;;
        --repo) TARGET_REPO="$2"; shift 2 ;;
        -h|--help) usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
done

# Pre-flight check
if ! command -v gh >/dev/null 2>&1; then
    echo "Error: GitHub CLI ('gh') is not installed. Install via: brew install gh (macOS) or see https://cli.github.com"
    exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
    echo "Error: GitHub CLI is not authenticated. Please run: gh auth login"
    exit 1
fi

REPO_FLAG=""
if [ -n "$TARGET_REPO" ]; then
    REPO_FLAG="--repo $TARGET_REPO"
fi

create_issue() {
    local title="$1"
    local labels="$2"
    local body="$3"

    echo "========================================================"
    echo "Title:  $title"
    echo "Labels: $labels"
    echo "========================================================"
    
    if [ "$DRY_RUN" = true ]; then
        echo -e "$body\n"
        echo "[DRY RUN] Skipped creation."
        echo ""
        return 0
    fi

    if [ "$INTERACTIVE" = true ]; then
        read -r -p "Create this issue? [y/N/q]: " choice
        case "$choice" in
            y|Y) ;;
            q|Q) echo "Aborted."; exit 0 ;;
            *) echo "Skipping issue."; echo ""; return 0 ;;
        esac
    fi

    # Create issue via gh CLI
    gh issue create $REPO_FLAG --title "$title" --label "$labels" --body "$body"
    echo "✓ Issue created."
    echo ""
}

echo "Starting GitHub Issue creation pipeline..."
echo ""

# ------------------------------------------------------------------------------
# Issue Definitions
# ------------------------------------------------------------------------------

# --- ISSUE 1 ---
TITLE_1="[Arch] Decouple Domain Services from Raw Database Client"
LABELS_1="architecture,refactor,priority:p1"
read -r -d '' BODY_1 << 'EOF' || true
### 📋 Summary & Nature of Issue
Domain services currently import database client implementations directly, preventing isolated unit testing and violating the Dependency Inversion Principle.

### 📍 Coordinates & Location
- **File:** `src/services/order.ts`
- **Lines:** `L24-L58`
- **Component:** `OrderProcessingService`

### ⚠️ Why It's a Problem
- **Tight Coupling:** The domain service cannot run in tests without a live PostgreSQL instance.
- **Leaky Database Types:** ORM queries are intermingled with business discount logic.

### 🛠️ Recommended Remediation
Introduce a repository interface (`IOrderRepository`) and inject it into `OrderService` constructor:

```typescript
export interface IOrderRepository {
  getOrder(id: string): Promise<Order>;
  saveOrder(order: Order): Promise<void>;
}
```

### 🔗 References
- Clean Architecture / Ports & Adapters guide
EOF
create_issue "$TITLE_1" "$LABELS_1" "$BODY_1"

echo "All issue tasks processed!"
